import {chromium} from '@playwright/test';
import {writeFile, mkdir} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
const target = process.argv[2] || pathToFileURL(resolve('dist/index.html')).href;
await mkdir('test-results', {recursive:true});
const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:1672,height:941},reducedMotion:'reduce'});
const results=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
const check=(name,pass)=>{results.push({name,pass:!!pass});if(!pass)throw Error(name)};
const wait=()=>page.waitForTimeout(230);
async function ready(){await page.locator('.micro-flat-canvas[data-ready=true]').waitFor();await wait()}
async function fit(){await page.getByRole('button',{name:'适应视口',exact:true}).click();await wait()}
async function point(id,n=0){return page.locator(`polygon[data-region=${id}]`).nth(n).evaluate(el=>{const p=el.getAttribute('points').split(' ').map(t=>t.split(',').map(Number)),r=el.ownerSVGElement.getBoundingClientRect();return{x:r.left+p.reduce((s,v)=>s+v[0],0)/4,y:r.top+p.reduce((s,v)=>s+v[1],0)/4,key:el.dataset.regionKey}})}
async function click(id,n=0){await fit();const p=await point(id,n);await page.mouse.click(p.x,p.y);await wait();return p}
try{
await page.goto(target);await page.locator('[data-renderer=ready]').waitFor();await page.getByRole('button',{name:'SM 内部',exact:true}).click();await wait();await page.getByRole('button',{name:'放大平铺',exact:true}).click();await ready();await page.getByRole('combobox',{name:'平铺视图架构'}).selectOption('tesla');await ready();
check('no second renderer or inset remains',await page.locator('.micro-detail-lens,.micro-lens-connector').count()===0&&await page.locator('.micro-workbench canvas').count()===1);
check('canvas spans body behind both side areas',await page.locator('.micro-flat-canvas').evaluate(e=>{const c=e.getBoundingClientRect(),b=e.closest('.micro-workbench-body').getBoundingClientRect();return Math.abs(c.left-b.left)<2&&Math.abs(c.width-b.width)<2}));
check('right card follows reference structure',await page.locator('.micro-inspector-topbar').isVisible()&&await page.locator('.micro-inspector-facts .micro-parameter-row').count()>=3);
check('left introduction has no opaque backdrop',await page.locator('.micro-intro').evaluate(e=>getComputedStyle(e).backgroundColor==='rgba(0, 0, 0, 0)'&&getComputedStyle(e).pointerEvents==='none'));
await page.screenshot({path:'test-results/GPU-Atlas-open-canvas-tesla.png'});
const old=await page.locator('.micro-explanation h3').innerText();await page.getByRole('button',{name:'下一个结构',exact:true}).click();await wait();check('next structure changes both selection and explanation',old!==await page.locator('.micro-explanation h3').innerText()&&await page.locator('.micro-explanation').getAttribute('data-region')===await page.locator('.micro-flat-canvas').getAttribute('data-selected-region'));
await page.getByRole('button',{name:'上一个结构',exact:true}).click();await wait();check('previous structure returns to original',old===await page.locator('.micro-explanation h3').innerText());
await page.getByRole('button',{name:'查看完整说明',exact:true}).click();check('full description can expand',await page.getByRole('button',{name:'收起说明',exact:true}).getAttribute('aria-expanded')==='true');
const key=await page.locator('.micro-explanation').getAttribute('data-region-key');await page.getByRole('button',{name:'收起结构说明',exact:true}).click();await wait();check('collapse restores canvas space',await page.locator('.micro-inspector').count()===0&&await page.getByRole('button',{name:'显示结构说明'}).isVisible());check('collapse preserves exact selection',await page.locator('.micro-flat-canvas').getAttribute('data-selected-region-key')===key);await page.getByRole('button',{name:'显示结构说明',exact:true}).click();await wait();check('restore keeps correct module',await page.locator('.micro-explanation').getAttribute('data-region-key')===key);
await page.getByRole('button',{name:'隐藏全部标签',exact:true}).click();await click('cuda');check('zoom fades introduction completely',await page.locator('.micro-intro').evaluate(e=>Number(getComputedStyle(e).opacity)===0));
const guide=await page.locator('.micro-framing-guide').boundingBox();const stage=await page.locator('.micro-flat-canvas').boundingBox();let p=await point('cuda');await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(stage.x+guide.x/2,p.y,{steps:8});await page.mouse.up();await wait();p=await point('cuda');check('model can move into former left column',p.x<guide.x&&p.x>stage.x);await page.mouse.click(p.x,p.y);await wait();check('real click in former left column still selects resource',await page.locator('.micro-explanation').getAttribute('data-region')==='cuda');await page.screenshot({path:'test-results/GPU-Atlas-open-canvas-zoom.png'});
await page.getByRole('button',{name:'收起结构说明',exact:true}).click();await fit();await page.screenshot({path:'test-results/GPU-Atlas-open-canvas-focus.png'});await page.getByRole('button',{name:'显示结构说明',exact:true}).click();await fit();
for(const g of ['tesla','fermi','kepler','maxwell','pascal','volta','turing','ampere','hopper','ada','blackwell']){await page.getByRole('combobox',{name:'平铺视图架构'}).selectOption(g);await ready();check(`${g}: inspector and canvas valid`,await page.locator('.micro-explanation').isVisible()&&await page.locator('.micro-flat-error').count()===0);check(`${g}: initial model is framed between floating text and card`,await page.locator('.micro-hit-regions polygon').evaluateAll(es=>{const canvas=es[0].closest('.micro-flat-canvas').getBoundingClientRect(),guide=es[0].closest('.micro-stage').querySelector('.micro-framing-guide').getBoundingClientRect();const coords=es.flatMap(e=>e.getAttribute('points').split(' ').map(p=>p.split(',').map(Number)));return Math.min(...coords.map(p=>p[0]))+canvas.left>=guide.left-2&&Math.max(...coords.map(p=>p[0]))+canvas.left<=guide.right+2}));}
await page.screenshot({path:'test-results/GPU-Atlas-open-canvas-blackwell.png'});
await page.locator('.micro-view-switch button').first().click();await ready();await page.screenshot({path:'test-results/GPU-Atlas-open-canvas-chip.png'});await click('sm');await ready();check('chip to SM actual drill remains available',await page.locator('.micro-flat-canvas').getAttribute('data-view')==='sm');
for(const width of [1024,768,390,320]){await page.setViewportSize({width,height:width<500?844:1000});await fit();check(`${width}px no horizontal overflow`,await page.locator('.micro-workbench').evaluate(e=>e.scrollWidth<=innerWidth));check(`${width}px readable card stays within viewport`,await page.locator('.micro-explanation').evaluate(e=>{const r=e.getBoundingClientRect();return e.scrollWidth<=e.clientWidth&&r.left>=0&&r.right<=innerWidth}));if(width===390)await page.screenshot({path:'test-results/GPU-Atlas-open-canvas-mobile.png'});}
check('no runtime errors',errors.length===0);
}finally{await writeFile('test-results/verification-open-canvas.json',JSON.stringify({results,errors},null,2));console.log(JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,errors}));await browser.close()}
