import { useCallback, useEffect, useRef, useState } from 'react';
import { Cpu, SquaresFour, ArrowsOut, CornersOut, Plus, Minus, ArrowUpRight, BookOpen, CirclesFour, Eye, EyeSlash, X } from '@phosphor-icons/react';
import { ARCHITECTURE_FACTS } from '../data/architectureFacts.js';
import { getTopologyDetails } from './topologyDetails.js';
import TopologyDiagram from './TopologyDiagram.jsx';
import './ArchitecturePanel.css';
const INITIAL_FRAME={zoom:1,x:0,y:0};
const clamp=(value,min,max)=>Math.min(max,Math.max(min,value));
export default function ArchitecturePanel({gpu,modeRequest,onSources}){
 const facts=ARCHITECTURE_FACTS[gpu.id],unit=gpu.smLabel||'SM';
 const [view,setView]=useState('chip'),[selected,setSelected]=useState('compute'),[activeGroup,setActiveGroup]=useState(0);
 const [frame,setFrame]=useState(INITIAL_FRAME),[labelsVisible,setLabelsVisible]=useState(true),[expanded,setExpanded]=useState(false);
 const canvasRef=useRef(null),workspaceRef=useRef(null),gesture=useRef(null),wasDragging=useRef(false),currentFrame=useRef(frame);currentFrame.current=frame;
 const chooseMode=useCallback(mode=>{setView(mode);setSelected(mode==='chip'?'compute':'cuda');setFrame(INITIAL_FRAME)},[]);
 useEffect(()=>{setActiveGroup(0);setSelected(view==='chip'?'compute':'cuda');setFrame(INITIAL_FRAME)},[gpu.id]);
 useEffect(()=>{if(modeRequest?.view)chooseMode(modeRequest.view)},[modeRequest,chooseMode]);
 const bounded=useCallback(value=>{const rect=canvasRef.current?.getBoundingClientRect(),zoom=clamp(value.zoom,1,2.5),maxX=(rect?.width||800)*(zoom-1)/2,maxY=(rect?.height||540)*(zoom-1)/2;return {zoom,x:clamp(value.x,-maxX,maxX),y:clamp(value.y,-maxY,maxY)}},[]);
 const zoomBy=useCallback(delta=>setFrame(previous=>bounded({...previous,zoom:Math.round((previous.zoom+delta)*100)/100})),[bounded]);
 const fit=()=>setFrame(INITIAL_FRAME);
 useEffect(()=>{const node=canvasRef.current;const wheel=event=>{if(!event.ctrlKey&&!event.metaKey&&!expanded)return;event.preventDefault();zoomBy(event.deltaY>0?-.08:.08)};node.addEventListener('wheel',wheel,{passive:false});const observer=new ResizeObserver(()=>setFrame(previous=>bounded(previous)));observer.observe(node);return()=>{node.removeEventListener('wheel',wheel);observer.disconnect()}},[bounded,zoomBy,expanded]);
 useEffect(()=>{if(!expanded)return;const previous=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';workspaceRef.current.querySelector('.ap-expand-button')?.focus();const keydown=event=>{if(event.key==='Escape'){event.preventDefault();setExpanded(false)}if(event.key==='Tab'){const items=[...workspaceRef.current.querySelectorAll('button:not(:disabled),a[href],summary,[tabindex="0"]')].filter(el=>el.getClientRects().length),first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus()}}};document.addEventListener('keydown',keydown);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',keydown);previous?.focus({preventScroll:true})}},[expanded]);
 const pointerDown=event=>{wasDragging.current=false;if(event.button!==0||currentFrame.current.zoom<=1)return;gesture.current={id:event.pointerId,x:event.clientX,y:event.clientY,frame:currentFrame.current,dragging:false}};
 const pointerMove=event=>{if(!event.buttons){gesture.current=null;return}const start=gesture.current;if(!start||start.id!==event.pointerId)return;const x=event.clientX-start.x,y=event.clientY-start.y;if(!start.dragging&&Math.hypot(x,y)<5)return;if(!start.dragging){start.dragging=true;event.currentTarget.setPointerCapture(event.pointerId)}wasDragging.current=true;setFrame(bounded({...start.frame,x:start.frame.x+x,y:start.frame.y+y}))};
 const pointerUp=event=>{if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);gesture.current=null};
 const tabKey=event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const mode=event.key==='Home'?'chip':event.key==='End'?'sm':view==='chip'?'sm':'chip';chooseMode(mode);document.getElementById(`ap-tab-${mode}`)?.focus()};
 const info=getTopologyDetails(gpu,facts,view,selected,activeGroup);
 const selectGroup=group=>{setActiveGroup(group);setSelected('compute')};
 const drill=group=>{if(typeof group==='number')setActiveGroup(group);chooseMode('sm')};
 const legend=view==='chip'?[['compute',facts.clusterLabel,'计算簇'],['sm',unit,'流式多处理器'],['cache',gpu.id==='tesla'?'纹理缓存':'L2 缓存'],['memory','内存控制器'],['io','其他模块']]:[['scheduler','调度'],['registers','寄存器'],['cuda','运算通路'],...(facts.sm.tensor?[['tensor','Tensor Core']]:[]),['shared','共享存储']];
 return <div className="architecture-panel">
  <div className="ap-heading"><div className="ap-heading-copy"><span className="ap-eyebrow">THE ARCHITECTURE COLLECTION</span><h2 id="topology-title">拉近视角。看见计算的内部。</h2><p>从一块显卡，进入晶体管构成的并行世界。</p></div><p className="ap-heading-intro">探索 {gpu.name} 架构下 {gpu.chip} 的{view==='chip'?'芯片拓扑':`${unit} 内部`}。<br/>透过交互式的逻辑视图，了解各个计算单元如何协同，把庞大的算力凝聚为真实的性能。</p><div className="ap-tabs" role="tablist" aria-label="架构观察层级">{[['chip','整颗芯片',Cpu],['sm',`${unit} 内部`,SquaresFour]].map(([mode,label,Icon])=><button type="button" key={mode} id={`ap-tab-${mode}`} role="tab" aria-controls="ap-diagram" aria-selected={view===mode} tabIndex={view===mode?0:-1} onKeyDown={tabKey} onClick={()=>chooseMode(mode)}><Icon size={19} aria-hidden="true"/>{label}</button>)}</div></div>
  <div ref={workspaceRef} className={`ap-workspace ${expanded?'is-expanded':''}`} role={expanded?'dialog':undefined} aria-modal={expanded?true:undefined} aria-label={expanded?`${gpu.name} 芯片全屏工作台`:undefined}>
   <div className="ap-viewport" id="ap-diagram" role="tabpanel" aria-labelledby={`ap-tab-${view}`}>
    <div className="ap-view-meta"><span><i/>{gpu.chip} / {view==='chip'?'CHIP TOPOLOGY':'STREAMING MULTIPROCESSOR'}</span><div><span>LOGICAL VIEW</span><button onClick={()=>setLabelsVisible(v=>!v)} aria-label={labelsVisible?'隐藏拓扑标签':'显示拓扑标签'} title={labelsVisible?'隐藏标签':'显示标签'}>{labelsVisible?<Eye size={17}/>:<EyeSlash size={17}/>}</button><button className="ap-expand-button" onClick={()=>setExpanded(v=>!v)} aria-label={expanded?'退出芯片全屏':'全屏查看芯片'} title={expanded?'退出全屏 (Esc)':'全屏查看'}>{expanded?<X size={20}/>:<ArrowsOut size={18}/>}</button></div></div>
    <div ref={canvasRef} className={`ap-canvas ${frame.zoom>1?'is-zoomed':''}`} tabIndex={0} aria-label="芯片图，可使用加号、减号缩放，数字 0 复位，放大后使用方向键平移" onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp} onClickCapture={event=>{if(wasDragging.current){event.stopPropagation();wasDragging.current=false}}} onKeyDown={event=>{if(event.target!==event.currentTarget)return;if(['+','=','-','0','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))event.preventDefault();if(event.key==='+'||event.key==='=')zoomBy(.15);else if(event.key==='-')zoomBy(-.15);else if(event.key==='0')fit();else if(event.key.startsWith('Arrow'))setFrame(previous=>bounded({...previous,x:previous.x+(event.key==='ArrowLeft'?35:event.key==='ArrowRight'?-35:0),y:previous.y+(event.key==='ArrowUp'?35:event.key==='ArrowDown'?-35:0)}))}}>
     <i className="ap-corner ap-corner-tl"/><i className="ap-corner ap-corner-tr"/><i className="ap-corner ap-corner-bl"/><i className="ap-corner ap-corner-br"/>
     <div className="ap-diagram-transform" style={{transform:`translate(${frame.x}px,${frame.y}px) scale(${frame.zoom})`}} data-zoom={Math.round(frame.zoom*100)}><TopologyDiagram gpu={gpu} view={view} selected={selected} activeGroup={activeGroup} onSelect={setSelected} onGroupSelect={selectGroup} onDrill={drill} labelsVisible={labelsVisible}/></div>
    </div>
    <div className="ap-view-footer"><div className="ap-legend" aria-label="功能区域图例">{legend.map(([id,title,detail])=><button key={id} title={detail||title} onClick={()=>id==='sm'?chooseMode('sm'):setSelected(id)} className={`ap-legend-${id} ${selected===id?'is-active':''}`}><i/><span>{title}</span></button>)}</div><div className="ap-zoom-controls"><div className="ap-zoom-stepper"><button disabled={frame.zoom<=1} onClick={()=>zoomBy(-.15)} aria-label="缩小芯片"><Minus size={15}/></button><output aria-live="polite" aria-label="芯片缩放比例">{Math.round(frame.zoom*100)}%</output><button disabled={frame.zoom>=2.5} onClick={()=>zoomBy(.15)} aria-label="放大芯片"><Plus size={15}/></button></div><button className="ap-fit-button" onClick={fit}><CornersOut size={17}/><span>适合窗口</span></button></div></div>
   </div>
   <aside className="ap-inspector" aria-label="所选模块说明"><div className="ap-inspector-top"><span>MODULE INSPECTOR</span><span>{view==='chip'?'01':'02'} / 02</span></div><div className="ap-inspector-content" key={`${gpu.id}-${view}-${selected}`} aria-live="polite"><div className="ap-selection"><CirclesFour size={22} weight="duotone"/>{info.eyebrow}</div><h3>{info.title}</h3><p className="ap-description">{info.text}</p><div className="ap-focus-stat"><strong>{info.stat}</strong><span>{info.statLabel}</span></div><dl className="ap-facts">{info.rows.map(([key,value])=><div className={key==='当前选中'?'is-current':''} key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></div><div className="ap-inspector-actions"><button className="ap-drill-button" onClick={()=>view==='chip'?drill(activeGroup):chooseMode('chip')}>{view==='chip'?`进入 ${unit} 内部`:'返回整颗芯片'}<ArrowUpRight size={19}/></button><details className="ap-config-note"><summary>配置口径与资料</summary><p>逻辑布局示意。完整 {gpu.chip} 为 {facts.fullClusters} {facts.clusterLabel} / {facts.fullSm} {unit}；{gpu.card} 启用 {facts.activeSm} {unit}。模块面积与位置不代表物理版图。</p>{facts.sources.slice(0,2).map(source=><a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.title}<ArrowUpRight size={13}/></a>)}</details></div></aside>
  </div>
  <div className="ap-resource-banner"><BookOpen size={34} weight="light" aria-hidden="true"/><div><strong>继续深入，探索更多架构细节。</strong><p>从 Tesla 到 Blackwell，阅读完整的架构演进与技术白皮书。</p></div><button onClick={onSources}>打开资料库<ArrowUpRight size={19}/></button></div><div className="ap-colophon"><span>GPU ATLAS<i/>让复杂的计算，看得见。</span><span>探索 · 学习 · 理解 · 更进一步</span></div>
 </div>;
}
